[build]
  command = "rm -f pnpm-lock.yaml && npm install --legacy-peer-deps && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_PACKAGE_MANAGER = "npm"
  NETLIFY_USE_PNPM = "false"
  NETLIFY_USE_YARN = "false"
  NPM_FLAGS = "--legacy-peer-deps"
  SKIP_INSTALL_DEPS = "false"

# Security headers for static deployment
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

# SPA redirects
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
