// Initial products data
export const initialProducts = [
  // Men's Glasses
  {
    id: 1,
    name: "Classic Round Glasses",
    price: 899,
    category: "Men",
    type: "Power Glasses",
    image: "/images/men-glasses-1.jpg",
    description: "Timeless round frames that suit most face shapes. Perfect for daily wear.",
    stock: 25,
    isNew: true,
    isBestSeller: false,
    featured: true,
    discount: 0,
    colors: ["Black", "Gold", "Silver"],
    material: "Metal",
    weight: "15g",
    dimensions: "135mm x 50mm x 20mm",
    gallery: ["/images/men-glasses-1.jpg", "/images/men-glasses-2.jpg", "/images/men-glasses-3.jpg"],
    frameSize: {
      width: 135,
      height: 40,
      bridge: 20,
      templeLength: 145,
    },
  },
  {
    id: 2,
    name: "Professional Rectangle Frames",
    price: 1199,
    category: "Men",
    type: "Power Glasses",
    image: "/images/men-glasses-2.jpg",
    description: "Modern rectangular frames perfect for office and professional settings.",
    stock: 30,
    isNew: false,
    isBestSeller: true,
    featured: true,
    discount: 15,
    colors: ["Black", "Brown", "Navy"],
    material: "Acetate",
    weight: "18g",
    dimensions: "140mm x 45mm x 18mm",
    gallery: ["/images/men-glasses-2.jpg", "/images/men-glasses-1.jpg", "/images/men-glasses-3.jpg"],
    frameSize: {
      width: 140,
      height: 42,
      bridge: 18,
      templeLength: 142,
    },
  },
  {
    id: 3,
    name: "Vintage Aviator Frames",
    price: 1399,
    category: "Men",
    type: "Power Glasses",
    image: "/images/men-glasses-3.jpg",
    description: "Classic aviator style adapted for prescription lenses.",
    stock: 20,
    isNew: false,
    isBestSeller: false,
    featured: false,
    discount: 0,
    colors: ["Gold", "Silver", "Black"],
    material: "Metal",
    weight: "16g",
    dimensions: "142mm x 48mm x 16mm",
    gallery: ["/images/men-glasses-3.jpg", "/images/men-glasses-1.jpg", "/images/men-glasses-2.jpg"],
    frameSize: {
      width: 142,
      height: 44,
      bridge: 16,
      templeLength: 145,
    },
  },

  // Women's Glasses
  {
    id: 4,
    name: "Cat Eye Elegance",
    price: 1299,
    category: "Women",
    type: "Power Glasses",
    image: "/images/women-glasses-1.jpg",
    description: "Elegant cat eye frames that add sophistication to any look.",
    stock: 18,
    isNew: false,
    isBestSeller: true,
    featured: true,
    discount: 10,
    colors: ["Black", "Tortoise", "Red"],
    material: "Acetate",
    weight: "17g",
    dimensions: "140mm x 52mm x 18mm",
    gallery: ["/images/women-glasses-1.jpg", "/images/women-glasses-2.jpg", "/images/women-glasses-3.jpg"],
    frameSize: {
      width: 140,
      height: 45,
      bridge: 18,
      templeLength: 140,
    },
  },
  {
    id: 5,
    name: "Butterfly Designer Frames",
    price: 1599,
    category: "Women",
    type: "Power Glasses",
    image: "/images/women-glasses-2.jpg",
    description: "Oversized butterfly frames for a glamorous and trendy look.",
    stock: 22,
    isNew: true,
    isBestSeller: false,
    featured: true,
    discount: 20,
    colors: ["Pink", "Purple", "Black"],
    material: "Acetate",
    weight: "19g",
    dimensions: "145mm x 55mm x 17mm",
    gallery: ["/images/women-glasses-2.jpg", "/images/women-glasses-1.jpg", "/images/women-glasses-3.jpg"],
    frameSize: {
      width: 145,
      height: 48,
      bridge: 17,
      templeLength: 138,
    },
  },
  {
    id: 6,
    name: "Minimalist Round Frames",
    price: 999,
    category: "Women",
    type: "Power Glasses",
    image: "/images/women-glasses-3.jpg",
    description: "Clean, minimalist design perfect for everyday wear.",
    stock: 35,
    isNew: false,
    isBestSeller: false,
    featured: false,
    discount: 0,
    colors: ["Rose Gold", "Silver", "Black"],
    material: "Metal",
    weight: "14g",
    dimensions: "138mm x 46mm x 19mm",
    gallery: ["/images/women-glasses-3.jpg", "/images/women-glasses-1.jpg", "/images/women-glasses-2.jpg"],
    frameSize: {
      width: 138,
      height: 42,
      bridge: 19,
      templeLength: 142,
    },
  },

  // Kids Glasses
  {
    id: 7,
    name: "Colorful Kids Frames",
    price: 699,
    category: "Kids",
    type: "Power Glasses",
    image: "/images/kids-glasses-1.jpg",
    description: "Durable and colorful frames designed specifically for children.",
    stock: 40,
    isNew: true,
    isBestSeller: true,
    featured: false,
    discount: 0,
    colors: ["Blue", "Red", "Green", "Pink"],
    material: "TR90",
    weight: "10g",
    dimensions: "125mm x 38mm x 15mm",
    gallery: ["/images/kids-glasses-1.jpg", "/images/kids-glasses-2.jpg"],
    frameSize: {
      width: 125,
      height: 35,
      bridge: 15,
      templeLength: 125,
    },
  },
  {
    id: 8,
    name: "Flexible Sports Frames",
    price: 799,
    category: "Kids",
    type: "Power Glasses",
    image: "/images/kids-glasses-2.jpg",
    description: "Flexible and unbreakable frames perfect for active kids.",
    stock: 30,
    isNew: false,
    isBestSeller: false,
    featured: false,
    discount: 15,
    colors: ["Blue", "Orange", "Purple"],
    material: "TR90",
    weight: "12g",
    dimensions: "128mm x 40mm x 16mm",
    gallery: ["/images/kids-glasses-2.jpg", "/images/kids-glasses-1.jpg"],
    frameSize: {
      width: 128,
      height: 38,
      bridge: 16,
      templeLength: 128,
    },
  },

  // Power Glasses / Computer Glasses
  {
    id: 9,
    name: "Blue Light Blockers Pro",
    price: 999,
    category: "Men",
    type: "Power Glasses",
    image: "/images/power-glasses-1.jpg",
    description: "Advanced blue light blocking technology for digital eye strain relief.",
    stock: 30,
    isNew: true,
    isBestSeller: false,
    featured: true,
    discount: 0,
    colors: ["Black", "Blue", "Transparent"],
    material: "TR90",
    weight: "12g",
    dimensions: "138mm x 48mm x 19mm",
    gallery: ["/images/power-glasses-1.jpg", "/images/power-glasses-2.jpg", "/images/power-glasses-3.jpg"],
    frameSize: {
      width: 138,
      height: 42,
      bridge: 19,
      templeLength: 142,
    },
  },
  {
    id: 10,
    name: "Computer Vision Glasses",
    price: 1199,
    category: "Women",
    type: "Power Glasses",
    image: "/images/power-glasses-2.jpg",
    description: "Specially designed for long hours of computer work and screen time.",
    stock: 25,
    isNew: false,
    isBestSeller: true,
    featured: false,
    discount: 25,
    colors: ["Black", "Brown", "Clear"],
    material: "Acetate",
    weight: "16g",
    dimensions: "140mm x 46mm x 18mm",
    gallery: ["/images/power-glasses-2.jpg", "/images/power-glasses-1.jpg", "/images/power-glasses-3.jpg"],
    frameSize: {
      width: 140,
      height: 44,
      bridge: 18,
      templeLength: 140,
    },
  },
  {
    id: 11,
    name: "Reading Glasses Deluxe",
    price: 899,
    category: "Men",
    type: "Power Glasses",
    image: "/images/power-glasses-3.jpg",
    description: "Premium reading glasses with anti-reflective coating.",
    stock: 35,
    isNew: false,
    isBestSeller: false,
    featured: false,
    discount: 0,
    colors: ["Black", "Brown", "Silver"],
    material: "Metal",
    weight: "15g",
    dimensions: "136mm x 44mm x 17mm",
    gallery: ["/images/power-glasses-3.jpg", "/images/power-glasses-1.jpg", "/images/power-glasses-2.jpg"],
    frameSize: {
      width: 136,
      height: 42,
      bridge: 17,
      templeLength: 138,
    },
  },

  // Sunglasses
  {
    id: 12,
    name: "Aviator Sunglasses Classic",
    price: 1499,
    category: "Men",
    type: "Sunglasses",
    image: "/images/sunglasses-men-1.jpg",
    description: "Classic aviator sunglasses with polarized lenses and UV protection.",
    stock: 12,
    isNew: false,
    isBestSeller: true,
    featured: true,
    discount: 0,
    colors: ["Gold", "Silver", "Black"],
    material: "Metal",
    weight: "16g",
    dimensions: "142mm x 51mm x 16mm",
    gallery: ["/images/sunglasses-men-1.jpg", "/images/sunglasses-2.jpg"],
    frameSize: {
      width: 142,
      height: 44,
      bridge: 16,
      templeLength: 145,
    },
  },
  {
    id: 13,
    name: "Designer Cat Eye Sunglasses",
    price: 1799,
    category: "Women",
    type: "Sunglasses",
    image: "/images/sunglasses-women-1.jpg",
    description: "Luxury cat eye sunglasses with gradient lenses and premium finish.",
    stock: 15,
    isNew: true,
    isBestSeller: false,
    featured: false,
    discount: 30,
    colors: ["Black", "Tortoise", "Pink"],
    material: "Acetate",
    weight: "20g",
    dimensions: "145mm x 55mm x 18mm",
    gallery: ["/images/sunglasses-women-1.jpg", "/images/sunglasses-1.jpg"],
    frameSize: {
      width: 145,
      height: 48,
      bridge: 18,
      templeLength: 140,
    },
  },
]

// Initial orders data
export const initialOrders = [
  {
    id: "ORD-001",
    customer: "Rahul Sharma",
    date: "2023-05-10",
    total: 2198,
    status: "Delivered",
    items: [
      { id: 1, name: "Classic Round Glasses", quantity: 1, price: 899 },
      { id: 9, name: "Blue Light Blockers Pro", quantity: 1, price: 999 },
      { id: "shipping", name: "Shipping", quantity: 1, price: 300 },
    ],
    contact: "+91 98765 43210",
    address: "123 Main St, Jaipur, Rajasthan",
    paymentMethod: "Cash on Delivery",
    notes: "Please deliver in the evening",
  },
  {
    id: "ORD-002",
    customer: "Priya Patel",
    date: "2023-05-12",
    total: 1599,
    status: "Processing",
    items: [
      { id: 12, name: "Aviator Sunglasses Classic", quantity: 1, price: 1499 },
      { id: "shipping", name: "Shipping", quantity: 1, price: 100 },
    ],
    contact: "+91 87654 32109",
    address: "456 Park Ave, Jaipur, Rajasthan",
    paymentMethod: "Credit Card",
    notes: "",
  },
  {
    id: "ORD-003",
    customer: "Amit Kumar",
    date: "2023-05-15",
    total: 2598,
    status: "Shipped",
    items: [
      { id: 4, name: "Cat Eye Elegance", quantity: 2, price: 1299 },
      { id: "shipping", name: "Shipping", quantity: 1, price: 0 },
    ],
    contact: "+91 76543 21098",
    address: "789 Lake View, Jaipur, Rajasthan",
    paymentMethod: "UPI",
    notes: "Gift wrap requested",
  },
]

// Initial settings data
export const initialSettings = {
  seo: {
    siteTitle: "C4 Chashma - Premium Eyewear Collection",
    siteDescription:
      "Discover stylish and affordable eyewear at C4 Chashma. Browse our collection of glasses, sunglasses, and power glasses for men, women, and kids.",
    siteKeywords: "eyewear, glasses, sunglasses, power glasses, C4 Chashma, optical shop",
  },
  contact: {
    phone: "+91 98765 43210",
    email: "info@c4chashma.com",
    address: "37/222, Rajat Path, Sector 37, Mansarovar, Jaipur, Rajasthan 302020",
    hours: "Monday - Saturday: 10:30 AM - 8:00 PM, Sunday: 11:00 AM - 6:00 PM",
  },
  social: {
    facebook: "https://facebook.com/c4chashma",
    instagram: "https://instagram.com/c4chashma",
    twitter: "https://twitter.com/c4chashma",
  },
  shipping: {
    freeShippingThreshold: 999,
    standardShippingRate: 99,
  },
}

// Initial categories data
export const initialCategories = [
  { id: 1, name: "Men", image: "/images/men-glasses-1.jpg", featured: true },
  { id: 2, name: "Women", image: "/images/women-glasses-1.jpg", featured: true },
  { id: 3, name: "Kids", image: "/images/kids-glasses-1.jpg", featured: true },
  { id: 4, name: "Power Glasses", image: "/images/power-glasses-1.jpg", featured: true },
  { id: 5, name: "Sunglasses", image: "/images/sunglasses-men-1.jpg", featured: true },
]

// Initial homepage data
export const initialHomepage = {
  hero: {
    title: "See the World Clearly",
    subtitle: "Discover our exclusive collection of stylish and affordable eyewear at C4 Chashma",
    image: "/images/glasses-hero-bg.jpg",
    buttonText: "Shop Now",
  },
  featuredTitle: "Featured Products",
  featuredSubtitle: "Our most popular frames, selected just for you",
  specialOffer: {
    title: "Buy One, Get One Free",
    subtitle:
      "Purchase any frame from our premium collection and get a second pair absolutely free. Offer valid for a limited time only.",
    image: "/images/glasses-hero-bg.jpg",
    buttonText: "Shop the Offer",
  },
  testimonialTitle: "What Our Customers Say",
  testimonialSubtitle: "Over 5,000 happy customers with 5-star Google reviews",
}

// Initial customers data
export const initialCustomers = [
  {
    id: 1,
    name: "Rahul Sharma",
    email: "rahul.sharma@example.com",
    phone: "+91 98765 43210",
    orders: 3,
    totalSpent: 5499,
    lastOrder: "2023-05-10",
  },
  {
    id: 2,
    name: "Priya Patel",
    email: "priya.patel@example.com",
    phone: "+91 87654 32109",
    orders: 1,
    totalSpent: 1599,
    lastOrder: "2023-05-12",
  },
  {
    id: 3,
    name: "Amit Kumar",
    email: "amit.kumar@example.com",
    phone: "+91 76543 21098",
    orders: 2,
    totalSpent: 3598,
    lastOrder: "2023-05-15",
  },
]

// Initial appointments data
export const initialAppointments = [
  {
    id: 1,
    customer: "Rahul Sharma",
    date: "2023-06-15",
    time: "10:30 AM",
    service: "Eye Test",
    status: "Completed",
    notes: "Prescription updated",
    contact: "+91 98765 43210",
  },
  {
    id: 2,
    customer: "Priya Patel",
    date: "2023-06-18",
    time: "2:00 PM",
    service: "Frame Fitting",
    status: "Scheduled",
    notes: "Looking for cat eye frames",
    contact: "+91 87654 32109",
  },
  {
    id: 3,
    customer: "Amit Kumar",
    date: "2023-06-20",
    time: "11:15 AM",
    service: "Eye Test",
    status: "Scheduled",
    notes: "",
    contact: "+91 76543 21098",
  },
]

// Initial discount codes data
export const initialDiscountCodes = [
  {
    id: 1,
    code: "WELCOME20",
    discount: 20,
    type: "Percentage",
    minOrder: 1000,
    maxDiscount: 500,
    validFrom: "2023-05-01",
    validTo: "2023-06-30",
    usageLimit: 100,
    usageCount: 45,
    active: true,
  },
  {
    id: 2,
    code: "SUMMER200",
    discount: 200,
    type: "Fixed",
    minOrder: 1500,
    maxDiscount: null,
    validFrom: "2023-06-01",
    validTo: "2023-08-31",
    usageLimit: 50,
    usageCount: 12,
    active: true,
  },
  {
    id: 3,
    code: "FIRSTORDER",
    discount: 10,
    type: "Percentage",
    minOrder: 0,
    maxDiscount: 200,
    validFrom: "2023-01-01",
    validTo: "2023-12-31",
    usageLimit: null,
    usageCount: 87,
    active: true,
  },
]

// Initial reviews data
export const initialReviews = [
  {
    id: 1,
    product: "Classic Round Glasses",
    productId: 1,
    customer: "Rahul Sharma",
    customerId: 1,
    rating: 5,
    review: "Excellent quality and perfect fit. Very comfortable to wear all day.",
    date: "2023-05-15",
    approved: true,
    title: "Perfect Everyday Glasses",
  },
  {
    id: 2,
    product: "Cat Eye Elegance",
    productId: 4,
    customer: "Priya Patel",
    customerId: 2,
    rating: 4,
    review: "Love the style and the quality is great. Very elegant design.",
    date: "2023-05-18",
    approved: true,
    title: "Stylish and Elegant",
  },
  {
    id: 3,
    product: "Blue Light Blockers Pro",
    productId: 9,
    customer: "Amit Kumar",
    customerId: 3,
    rating: 5,
    review: "These have really helped reduce my eye strain during long work hours. Highly recommend!",
    date: "2023-05-20",
    approved: false,
    title: "Game Changer for Work",
  },
]

// Initial stores data
export const initialStores = [
  {
    id: 1,
    name: "C4 Chashma - Main Store",
    address: "37/222, Rajat Path, Sector 37, Mansarovar, Jaipur, Rajasthan 302020",
    phone: "+91 98765 43210",
    email: "mainstore@c4chashma.com",
    hours: "Monday - Saturday: 10:30 AM - 8:00 PM, Sunday: 11:00 AM - 6:00 PM",
    coordinates: {
      latitude: 26.8535,
      longitude: 75.7654,
    },
    services: ["Eye Tests", "Frame Fitting", "Contact Lens Fitting", "Repairs"],
    image: "/images/glasses-hero-bg.jpg",
    featured: true,
  },
  {
    id: 2,
    name: "C4 Chashma - City Center",
    address: "Shop 12, City Mall, MI Road, Jaipur, Rajasthan 302001",
    phone: "+91 87654 32109",
    email: "citycenter@c4chashma.com",
    hours: "Monday - Sunday: 11:00 AM - 9:00 PM",
    coordinates: {
      latitude: 26.9124,
      longitude: 75.7873,
    },
    services: ["Frame Fitting", "Quick Repairs", "Sunglasses Collection"],
    image: "/images/glasses-hero-bg.jpg",
    featured: true,
  },
]

// Initial prescriptions data
export const initialPrescriptions = [
  {
    id: 1,
    customerId: 1,
    customerName: "Rahul Sharma",
    date: "2023-03-10",
    doctor: "Dr. Sharma",
    rightEye: {
      sphere: "-2.25",
      cylinder: "-0.75",
      axis: "180",
      pd: "32",
    },
    leftEye: {
      sphere: "-2.00",
      cylinder: "-0.50",
      axis: "175",
      pd: "32",
    },
    addPower: "+1.00",
    notes: "Patient experiencing eye strain with computer work",
    expiryDate: "2024-03-10",
    image: "/placeholder.svg?height=400&width=300",
    verified: true,
  },
]

// Initial frame sizes data
export const initialFrameSizes = [
  {
    id: 1,
    name: "Small",
    width: "128-135mm",
    height: "35-40mm",
    bridge: "16-18mm",
    templeLength: "135-140mm",
    faceShape: ["Round", "Oval"],
    description: "Ideal for smaller face shapes",
    image: "/images/kids-glasses-1.jpg",
  },
  {
    id: 2,
    name: "Medium",
    width: "136-142mm",
    height: "40-45mm",
    bridge: "18-20mm",
    templeLength: "140-145mm",
    faceShape: ["Oval", "Square", "Heart"],
    description: "Versatile size that fits most face shapes",
    image: "/images/men-glasses-1.jpg",
  },
]

// Initial marketing campaigns data
export const initialMarketingCampaigns = [
  {
    id: 1,
    name: "Summer Sale 2023",
    type: "Discount",
    startDate: "2023-06-01",
    endDate: "2023-08-31",
    status: "Active",
    budget: 15000,
    target: "All Customers",
    channels: ["Email", "SMS", "Social Media"],
    discountCode: "SUMMER200",
    description: "Summer sale with 20% off on all sunglasses",
  },
]

// Initial virtual try-on data
export const initialVirtualTryOn = {
  enabled: true,
  instructions:
    "1. Allow camera access\n2. Position your face in the frame\n3. Try on different frames\n4. Take a screenshot to save your look",
  compatibleProducts: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
  faceShapes: ["Round", "Oval", "Square", "Heart", "Diamond", "Rectangle"],
  recommendationEnabled: true,
  privacyNotice: "We do not store your camera feed or images. All processing is done locally on your device.",
  feedbackEnabled: true,
}
