// Initial data for the admin panel
export const initialData = {
  // Products data
  products: [
    {
      id: "1",
      name: "Classic Round Eyeglasses",
      category: "Eyeglasses",
      price: 129.99,
      discountPrice: 99.99,
      stock: 45,
      sku: "EG-CR-001",
      description: "Timeless round eyeglasses with a thin metal frame, perfect for any face shape.",
      features: ["UV Protection", "Anti-Glare", "Scratch Resistant"],
      images: ["/placeholder.svg?height=200&width=200"],
      colors: ["Black", "Gold", "Silver"],
      frameSize: ["Small", "Medium", "Large"],
      status: "active",
      createdAt: "2023-01-15T10:30:00Z",
      updatedAt: "2023-04-20T14:15:00Z",
    },
    {
      id: "2",
      name: "Designer Aviator Sunglasses",
      category: "Sunglasses",
      price: 199.99,
      discountPrice: 159.99,
      stock: 28,
      sku: "SG-DA-002",
      description: "Premium aviator sunglasses with polarized lenses and gold-plated frames.",
      features: ["Polarized", "100% UV Protection", "Impact Resistant"],
      images: ["/placeholder.svg?height=200&width=200"],
      colors: ["Gold/Green", "Silver/Blue", "Black/Gray"],
      frameSize: ["Medium", "Large"],
      status: "active",
      createdAt: "2023-02-10T09:45:00Z",
      updatedAt: "2023-05-05T11:20:00Z",
    },
    {
      id: "3",
      name: "Blue Light Blocking Glasses",
      category: "Computer Glasses",
      price: 89.99,
      stock: 0,
      sku: "CG-BL-003",
      description: "Protect your eyes from digital strain with these stylish blue light blocking glasses.",
      features: ["Blue Light Filtering", "Anti-Glare", "Lightweight"],
      images: ["/placeholder.svg?height=200&width=200"],
      colors: ["Black", "Tortoise", "Clear"],
      frameSize: ["Small", "Medium", "Large"],
      status: "out-of-stock",
      createdAt: "2023-03-05T13:15:00Z",
      updatedAt: "2023-06-12T16:40:00Z",
    },
    {
      id: "4",
      name: "Cat-Eye Prescription Frames",
      category: "Eyeglasses",
      price: 149.99,
      stock: 32,
      sku: "EG-CE-004",
      description: "Elegant cat-eye frames that add a touch of vintage glamour to any outfit.",
      features: ["Prescription Ready", "Spring Hinges", "Acetate Frame"],
      images: ["/placeholder.svg?height=200&width=200"],
      colors: ["Black", "Red", "Tortoise"],
      frameSize: ["Small", "Medium"],
      status: "active",
      createdAt: "2023-03-22T08:30:00Z",
      updatedAt: "2023-06-18T10:05:00Z",
    },
    {
      id: "5",
      name: "Sport Wrap Sunglasses",
      category: "Sunglasses",
      price: 179.99,
      stock: 5,
      sku: "SG-SW-005",
      description: "High-performance wrap sunglasses designed for sports and outdoor activities.",
      features: ["Polarized", "Impact Resistant", "Water Repellent"],
      images: ["/placeholder.svg?height=200&width=200"],
      colors: ["Black/Red", "White/Blue"],
      frameSize: ["Medium", "Large"],
      status: "active",
      createdAt: "2023-04-08T15:20:00Z",
      updatedAt: "2023-07-01T09:30:00Z",
    },
  ],

  // Categories data
  categories: [
    { id: "1", name: "Eyeglasses", description: "Prescription and non-prescription eyeglasses", isActive: true },
    { id: "2", name: "Sunglasses", description: "UV protection sunglasses", isActive: true },
    { id: "3", name: "Computer Glasses", description: "Blue light blocking glasses", isActive: true },
    { id: "4", name: "Contact Lenses", description: "Daily, weekly and monthly contact lenses", isActive: true },
    { id: "5", name: "Accessories", description: "Cases, solutions, and other accessories", isActive: true },
  ],

  // Orders data
  orders: [
    {
      id: "ORD-001",
      customer: "John Doe",
      customerId: "1",
      date: "2023-05-15T10:30:00Z",
      total: 299.98,
      status: "Delivered",
      paymentMethod: "Credit Card",
      contact: "+91 98765 43210",
      address: "123 Main St, Mumbai, Maharashtra, 400001",
      items: [
        { name: "Classic Round Eyeglasses", price: 99.99, quantity: 2 },
        { name: "Lens Cleaning Kit", price: 49.99, quantity: 2 },
      ],
    },
    {
      id: "ORD-002",
      customer: "Jane Smith",
      customerId: "2",
      date: "2023-05-18T14:45:00Z",
      total: 159.99,
      status: "Shipped",
      paymentMethod: "PayPal",
      contact: "+91 87654 32109",
      address: "456 Park Ave, Delhi, 110001",
      items: [{ name: "Designer Aviator Sunglasses", price: 159.99, quantity: 1 }],
    },
    {
      id: "ORD-003",
      customer: "Mike Johnson",
      customerId: "3",
      date: "2023-05-20T09:15:00Z",
      total: 89.99,
      status: "Processing",
      paymentMethod: "UPI",
      contact: "+91 76543 21098",
      address: "789 Oak St, Bangalore, Karnataka, 560001",
      items: [{ name: "Blue Light Blocking Glasses", price: 89.99, quantity: 1 }],
    },
    {
      id: "ORD-004",
      customer: "Sarah Williams",
      customerId: "4",
      date: "2023-05-22T16:30:00Z",
      total: 329.98,
      status: "Processing",
      paymentMethod: "Credit Card",
      contact: "+91 65432 10987",
      address: "321 Pine St, Chennai, Tamil Nadu, 600001",
      items: [
        { name: "Cat-Eye Prescription Frames", price: 149.99, quantity: 2 },
        { name: "Lens Cleaning Solution", price: 29.99, quantity: 1 },
      ],
    },
  ],

  // Customers data
  customers: [
    {
      id: "1",
      name: "John Doe",
      email: "john.doe@example.com",
      phone: "+91 98765 43210",
      location: "Mumbai",
      joinDate: "2023-01-10T08:30:00Z",
      orders: 5,
      totalSpent: 1299.95,
      lastOrder: "2023-05-15T10:30:00Z",
      loyaltyPoints: 130,
    },
    {
      id: "2",
      name: "Jane Smith",
      email: "jane.smith@example.com",
      phone: "+91 87654 32109",
      location: "Delhi",
      joinDate: "2023-02-15T10:45:00Z",
      orders: 3,
      totalSpent: 759.97,
      lastOrder: "2023-05-18T14:45:00Z",
      loyaltyPoints: 75,
    },
    {
      id: "3",
      name: "Mike Johnson",
      email: "mike.johnson@example.com",
      phone: "+91 76543 21098",
      location: "Bangalore",
      joinDate: "2023-03-05T09:15:00Z",
      orders: 2,
      totalSpent: 279.98,
      lastOrder: "2023-05-20T09:15:00Z",
      loyaltyPoints: 28,
    },
    {
      id: "4",
      name: "Sarah Williams",
      email: "sarah.williams@example.com",
      phone: "+91 65432 10987",
      location: "Chennai",
      joinDate: "2023-03-20T14:30:00Z",
      orders: 1,
      totalSpent: 329.98,
      lastOrder: "2023-05-22T16:30:00Z",
      loyaltyPoints: 33,
    },
  ],

  // Appointments data
  appointments: [
    {
      id: "1",
      customer: "John Doe",
      date: "2023-05-25",
      time: "10:00 AM",
      service: "Eye Test",
      doctor: "Dr. Sharma",
      status: "Scheduled",
      notes: "First time customer",
      phone: "+91 98765 43210",
    },
    {
      id: "2",
      customer: "Jane Smith",
      date: "2023-05-26",
      time: "11:30 AM",
      service: "Frame Fitting",
      doctor: "Dr. Patel",
      status: "Scheduled",
      notes: "Looking for designer frames",
      phone: "+91 87654 32109",
    },
    {
      id: "3",
      customer: "Mike Johnson",
      date: "2023-05-24",
      time: "2:00 PM",
      service: "Contact Lens Fitting",
      doctor: "Dr. Mehta",
      status: "Completed",
      notes: "First time wearing contacts",
      phone: "+91 76543 21098",
    },
  ],

  // Discount codes data
  discountCodes: [
    {
      id: "1",
      code: "WELCOME20",
      type: "percentage",
      value: 20,
      minPurchase: 1000,
      maxUses: 100,
      usedCount: 45,
      startDate: "2023-01-01T00:00:00Z",
      endDate: "2023-12-31T23:59:59Z",
      active: true,
    },
    {
      id: "2",
      code: "SUMMER2023",
      type: "percentage",
      value: 15,
      minPurchase: 0,
      maxUses: null,
      usedCount: 78,
      startDate: "2023-05-01T00:00:00Z",
      endDate: "2023-08-31T23:59:59Z",
      active: true,
    },
    {
      id: "3",
      code: "FREESHIP",
      type: "fixed",
      value: 100,
      minPurchase: 1500,
      maxUses: null,
      usedCount: 120,
      startDate: "2023-03-01T00:00:00Z",
      endDate: "2023-12-31T23:59:59Z",
      active: true,
    },
  ],

  // Reviews data
  reviews: [
    {
      id: "1",
      customer: "John Doe",
      product: "Classic Round Eyeglasses",
      rating: 5,
      text: "These glasses are amazing! The quality is excellent and they fit perfectly.",
      date: "2023-04-15T10:30:00Z",
      approved: true,
    },
    {
      id: "2",
      customer: "Jane Smith",
      product: "Designer Aviator Sunglasses",
      rating: 4,
      text: "Great sunglasses, very stylish and good UV protection. A bit pricey though.",
      date: "2023-04-20T14:45:00Z",
      approved: true,
      reply: "Thank you for your feedback! We focus on quality materials which affects the price.",
      replyDate: "2023-04-21T09:30:00Z",
    },
    {
      id: "3",
      customer: "Mike Johnson",
      product: "Blue Light Blocking Glasses",
      rating: 3,
      text: "They work well for reducing eye strain, but the frame feels a bit flimsy.",
      date: "2023-05-05T16:20:00Z",
      approved: false,
    },
  ],

  // Stores data
  stores: [
    {
      id: "1",
      name: "C4 Chashma - Bandra",
      address: "24, Hill Road",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400050",
      phone: "+91 98765 43210",
      email: "bandra@c4chashma.com",
      openingHours: {
        monday: { open: "10:00", close: "19:00", closed: false },
        tuesday: { open: "10:00", close: "19:00", closed: false },
        wednesday: { open: "10:00", close: "19:00", closed: false },
        thursday: { open: "10:00", close: "19:00", closed: false },
        friday: { open: "10:00", close: "19:00", closed: false },
        saturday: { open: "10:00", close: "19:00", closed: false },
        sunday: { open: "11:00", close: "17:00", closed: false },
      },
      services: ["Eye Tests", "Frame Fitting", "Contact Lens Fitting"],
      doctors: [
        { name: "Dr. Sharma", specialization: "Optometrist", days: ["Monday", "Wednesday", "Friday"] },
        { name: "Dr. Patel", specialization: "Ophthalmologist", days: ["Tuesday", "Thursday"] },
      ],
    },
    {
      id: "2",
      name: "C4 Chashma - Andheri",
      address: "Shop 5, Infiniti Mall",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400053",
      phone: "+91 98765 43211",
      email: "andheri@c4chashma.com",
      openingHours: {
        monday: { open: "11:00", close: "21:00", closed: false },
        tuesday: { open: "11:00", close: "21:00", closed: false },
        wednesday: { open: "11:00", close: "21:00", closed: false },
        thursday: { open: "11:00", close: "21:00", closed: false },
        friday: { open: "11:00", close: "21:00", closed: false },
        saturday: { open: "11:00", close: "21:00", closed: false },
        sunday: { open: "11:00", close: "21:00", closed: false },
      },
      services: ["Eye Tests", "Frame Fitting", "Contact Lens Fitting", "Sunglasses Customization"],
      doctors: [
        { name: "Dr. Mehta", specialization: "Optometrist", days: ["Monday", "Tuesday", "Wednesday"] },
        { name: "Dr. Singh", specialization: "Ophthalmologist", days: ["Thursday", "Friday", "Saturday"] },
      ],
    },
  ],

  // Blog data
  blogPosts: [
    {
      id: "1",
      title: "Top 5 Eyewear Trends for 2023",
      slug: "top-5-eyewear-trends-2023",
      excerpt: "Discover the hottest eyewear trends that are dominating the fashion scene this year.",
      content:
        "# Top 5 Eyewear Trends for 2023\n\nEyewear fashion is constantly evolving, and 2023 brings exciting new trends...",
      featuredImage: "/placeholder.svg?height=400&width=600",
      author: "Sarah Johnson",
      category: "Fashion",
      tags: ["trends", "fashion", "eyewear", "2023"],
      publishDate: "2023-03-15",
      status: "published",
      seoTitle: "Top 5 Eyewear Trends for 2023 | C4 Chashma",
      seoDescription:
        "Discover the hottest eyewear trends that are dominating the fashion scene in 2023. From oversized frames to sustainable materials.",
      seoKeywords: ["eyewear trends 2023", "fashion eyewear", "trendy glasses", "sunglasses trends"],
    },
    {
      id: "2",
      title: "How to Choose the Right Frames for Your Face Shape",
      slug: "choose-right-frames-face-shape",
      excerpt: "Learn how to select the perfect eyeglass frames that complement your unique face shape.",
      content:
        "# How to Choose the Right Frames for Your Face Shape\n\nFinding the perfect pair of glasses involves more than just picking a style you like...",
      featuredImage: "/placeholder.svg?height=400&width=600",
      author: "Michael Chen",
      category: "Guides",
      tags: ["face shape", "frames", "style guide", "eyeglasses"],
      publishDate: "2023-02-28",
      status: "published",
      seoTitle: "How to Choose Frames for Your Face Shape | C4 Chashma",
      seoDescription:
        "Learn how to select the perfect eyeglass frames that complement your unique face shape. Expert tips for oval, round, square, and heart-shaped faces.",
      seoKeywords: [
        "frames for face shape",
        "eyeglass frame selection",
        "best glasses for face shape",
        "face shape guide",
      ],
    },
  ],

  blogCategories: [
    { id: "1", name: "Fashion", slug: "fashion", description: "Latest eyewear fashion trends and style tips" },
    { id: "2", name: "Health", slug: "health", description: "Eye health information and advice" },
    { id: "3", name: "Guides", slug: "guides", description: "How-to guides and tutorials" },
    { id: "4", name: "News", slug: "news", description: "Latest news from C4 Chashma and the eyewear industry" },
  ],

  blogAuthors: [
    {
      id: "1",
      name: "Sarah Johnson",
      bio: "Fashion editor with 10+ years of experience in the eyewear industry",
      avatar: "/placeholder.svg?height=100&width=100",
    },
    {
      id: "2",
      name: "Michael Chen",
      bio: "Style consultant and eyewear specialist",
      avatar: "/placeholder.svg?height=100&width=100",
    },
    {
      id: "3",
      name: "Dr. Emily Rodriguez",
      bio: "Optometrist with a focus on digital eye strain and eye health",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  ],

  // Homepage settings
  homepageSettings: {
    hero: {
      slides: [
        {
          id: "1",
          title: "See the World in Style",
          subtitle: "Discover our premium collection of eyewear that combines fashion, comfort, and quality.",
          buttonText: "Shop Now",
          buttonLink: "/products",
          image: "/placeholder.svg?height=800&width=1600",
          isActive: true,
        },
        {
          id: "2",
          title: "New Summer Collection",
          subtitle: "Protect your eyes with our stylish sunglasses collection.",
          buttonText: "Explore",
          buttonLink: "/products?category=sunglasses",
          image: "/placeholder.svg?height=800&width=1600",
          isActive: true,
        },
      ],
      autoplay: true,
      interval: 5000,
    },
    featuredCategories: {
      title: "Shop By Category",
      subtitle: "Find the perfect eyewear for your style and needs",
      categories: [
        {
          id: "1",
          name: "Men's Eyewear",
          image: "/placeholder.svg?height=300&width=300",
          link: "/products?category=men",
          isActive: true,
          order: 1,
        },
        {
          id: "2",
          name: "Women's Eyewear",
          image: "/placeholder.svg?height=300&width=300",
          link: "/products?category=women",
          isActive: true,
          order: 2,
        },
        {
          id: "3",
          name: "Kids' Eyewear",
          image: "/placeholder.svg?height=300&width=300",
          link: "/products?category=kids",
          isActive: true,
          order: 3,
        },
      ],
      isActive: true,
    },
    featuredProducts: {
      title: "Featured Products",
      subtitle: "Our most popular frames, selected just for you",
      productIds: ["1", "2", "3", "4"],
      isActive: true,
    },
    promotionBanner: {
      title: "Buy One, Get One Free",
      subtitle:
        "Purchase any frame from our premium collection and get a second pair absolutely free. Offer valid for a limited time only.",
      buttonText: "Shop the Offer",
      buttonLink: "/products?promotion=bogo",
      image: "/placeholder.svg?height=400&width=600",
      backgroundColor: "#1f2937",
      isActive: true,
    },
    testimonials: {
      title: "What Our Customers Say",
      subtitle: "Read reviews from our satisfied customers",
      isActive: true,
    },
    virtualTryOn: {
      title: "Try Before You Buy",
      subtitle:
        "Experience our virtual try-on technology. See how different frames look on your face without leaving home.",
      buttonText: "Try Now",
      buttonLink: "/virtual-try-on",
      image: "/placeholder.svg?height=300&width=400",
      isActive: true,
    },
  },

  // General settings
  settings: {
    seo: {
      siteTitle: "C4 Chashma - Premium Eyewear Store",
      siteDescription: "Shop the latest eyeglasses, sunglasses, and contact lenses at C4 Chashma.",
      siteKeywords: "eyeglasses, sunglasses, contact lenses, eye care, prescription glasses",
    },
    contact: {
      phone: "+91 98765 43210",
      email: "info@c4chashma.com",
      address: "24, Hill Road, Bandra West, Mumbai, Maharashtra 400050",
      hours: "Monday-Saturday: 10:00 AM - 7:00 PM, Sunday: 11:00 AM - 5:00 PM",
    },
    social: {
      facebook: "https://facebook.com/c4chashma",
      instagram: "https://instagram.com/c4chashma",
      twitter: "https://twitter.com/c4chashma",
    },
    shipping: {
      freeShippingThreshold: 1500,
      standardShippingRate: 100,
    },
  },
}
